server:
  port: 8080
  mode: release
  
  tls:
    enabled: true
    cert_file: "configs/server.crt"
    key_file: "configs/server.key"
    auto_gen: true

security:
  api_key: "xxxxxx"

virtualizor:
  host: "127.0.0.1"
  port: 4085
  api_key: "xxxxxxx"
  api_password: "xxxxxxxx"
  timeout: 30
  skip_verify: true

logging:
  level: "info"
  file: "logs/app.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

